on:
  pull_request:
    types: [opened]
jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Add some useful instructions to PR creator
    steps:
      - uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: >
            "SUGGESTION:
            1. Build custom container here: https://github.com/skalenetwork/skaled/actions?query=workflow%3A%22Custom+Docker+and+Binary%22
            2. Test it here: https://github.com/skalenetwork/skale-ci-integration_tests/actions?query=workflow%3A%22Skaled+Nightly+Tests%22
            "
    
